---
title: "init"
format: pdf
editor_options: 
  chunk_output_type: console
---

```{r install-pkgs}
options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages("tidyverse")
```

```{r pkgs-libraries}
#| message: FALSE

library(tidyverse)
library(readr)
```


```{r}
# might take a while, took 1-2 min on my system
# works on container
tigercensus_raw <- read_csv('~/data/2026-ASA-DataFest-Data-Files/tigercensuscodes.csv',show_col_types = FALSE)
determinants_raw <- read_csv('~/data/2026-ASA-DataFest-Data-Files/social_determinants.csv',show_col_types = FALSE)
providers_raw <- read_csv('~/data/2026-ASA-DataFest-Data-Files/providers.csv',show_col_types = FALSE)
patients_raw <- read_csv('~/data/2026-ASA-DataFest-Data-Files/patients.csv',show_col_types = FALSE)
encounters_raw <- read_csv('~/data/2026-ASA-DataFest-Data-Files/encounters.csv',show_col_types = FALSE)
diagnosis_raw <- read_csv('~/data/2026-ASA-DataFest-Data-Files/diagnosis.csv',show_col_types = FALSE)
departments_raw <- read_csv('~/data/2026-ASA-DataFest-Data-Files/departments.csv',show_col_types = FALSE)

```

```{r}
#| label: departments_cleaning
#| eval: false

clean_df <- function(df) {
  return(df |>
    janitor::clean_names() |>
     mutate(across(everything(), \(x) ifelse(str_detect(x, "\\*|Unknown|Unspecified"), NA, x)))
  )
}

departments <- clean_df(departments_raw) |>
  filter(department_key > 0)
determinants <- clean_df(determinants_raw) 
encounters <- clean_df(encounters_raw) |>
  mutate(date = as.Date(date, format = "%m/%d/%y"), visit_type = str_to_title(visit_type))
diagnosis <- clean_df(diagnosis_raw)
patients <- clean_df(patients_raw)
providers <- clean_df(providers_raw) |>
  mutate(across(-c(durable_key, clinician_title), \(x) str_to_title(x)), 
         office_address = str_remove_all(office_address,
                                          "\\."),
         office_address = str_replace_all(office_address,
                                          "Ste", "Suite"),
         office_address = str_replace_all(office_address,
                                          "St", "Street"),
         office_address = str_replace_all(office_address, "Rd", "Road"),
         office_address = str_replace_all(office_address, "Dr", "Drive"),
         office_address = str_replace_all(office_address,
                                          "\\b(\\w{1,2})\\b",
                                          \(x) str_to_upper(x)),
         office_address = str_replace_all(office_address, "Street", "St"),
         office_address = str_replace_all(office_address, "Road", "Rd"),
         office_address = str_replace_all(office_address, "Drive", "Dr"),
         office_address = str_replace_all(office_address, "Suite", "Ste"),
         clinician_title = str_remove_all(clinician_title, "\\.")
         )
tigercensus <- clean_df(tigercensus_raw)
```

```{r}
#| label: read-clean-dfs

departments <- read_csv("../Clean-Data/departments.csv") |>
  mutate(county = str_to_title(county), department_name = str_to_title(department_name))
determinants <- read_csv( "../Clean-Data/determinants.csv")
diagnosis <- read_csv("../Clean-Data/diagnosis.csv")
encounters <- read_csv("../Clean-Data/encounters.csv") 
patients <- read_csv("../Clean-Data/patients.csv")
providers <- read_csv("../Clean-Data/providers.csv") |>
  mutate(office_address = str_replace(office_address, "CT", "Ct"))
tigercensus <- read_csv("../Clean-Data/tigercensus.csv")
```

# Census Median Household income
```{r}
ks_income_tract <- get_acs(
  geography = "tract",   # Choose county as our geographic unit
  variables = "B19013_001", 
  state = "KS",         
  year = 2022,
  geometry = TRUE)

ks_income_tract <- ks_income_tract |> 
  mutate(
  NAME = str_remove_all(NAME, ";"),
  NAME = str_remove_all(NAME, "Census Tract"),
  NAME = str_remove_all(NAME, "County"),
  NAME = str_remove_all(NAME, "Kansas"),
  NAME = str_squish(NAME)
) %>% 
  separate(NAME, into = c("tract", "county_name"), sep = " ")
```

SVH only covers 19 counties

```{r}
svh_counties <- tibble(
  county = c("Shawnee", "Riley", "Geary", "Dickinson", "Clay", "Wabaunsee", 
             "Morris", "Pottawatomie", "Jefferson", "Atchison", "Jackson", 
             "Nemaha", "Marshall", "Brown", "Lyon", "Franklin", "Osage", 
             "Coffey", "Douglas"),
  fips = c("20177", "20161", "20085", "20057", "20029", "20207", "20129", 
           "20149", "20103", "20015", "20099", "20135", "20121", "20021", 
           "20111", "20063", "20141", "20041", "20061")
)

ks_income_tract <- svh_counties %>% 
  left_join(ks_income_tract, by = join_by(county == county_name))
```

# getting tract data

```{r}
#| message: FALSE
kansas_tract <- tigris::tracts(state = "KS", year = 2024, progress_bar = FALSE) |> 
  janitor::clean_names() 
```

# Median HH income geospatial plot

```{r}
ks_sf_income_tract <- ks_income_tract %>%
  left_join(kansas_tract, by = c("GEOID" = "geoid")) %>% 
  sf::st_as_sf()

ggplot(ks_sf_income_tract) +
  geom_sf(aes(fill = estimate), color = NA) +
  scale_fill_viridis_c(name = "Median Household\nIncome ($)") +
  theme_minimal() +
  labs(title = "Median Household Income by Census Tract in Kansas")
```
