---
title: "viz"
format: html
---

```{r}
#| label: libraries

library(tidyverse)
library(tigris)
library(sf)
library(ggthemes)
library(scales)
library(colorspace)
```

```{r}
#| label: read-in-data

file_path_header <- "~/Downloads/datafest2026/Clean-Data"

departments <- read_csv(file.path(file_path_header, "departments.csv")) |>
  mutate(county = str_to_title(county), department_name = str_to_title(department_name))
determinants <- read_csv(file.path(file_path_header, "determinants.csv"))
diagnosis <- read_csv(file.path(file_path_header, "diagnosis.csv"))
encounters <- read_csv(file.path(file_path_header, "encounters.csv"))
patients <- read_csv(file.path(file_path_header, "patients.csv"))
providers <- read_csv(file.path(file_path_header, "providers.csv")) |> 
  mutate(office_address = str_replace(office_address, "CT", "Ct"))
tigercensus <- read_csv(file.path(file_path_header, "tigercensus.csv"))
```
```{r}
svh_locations <- read_csv("~/chelseanathan0608@gmail.com - Google Drive/My Drive/Datafest/SVH Locations (2).csv")
svh_locations <- svh_locations %>%
  st_as_sf(coords = c("Latitude", "Longitude"), crs = 4326)
```



```{r}
#| label: get-ks-shapefile
#| cache: true

#kansas_county <- counties(state = "KS", year = 2024, progress_bar = FALSE) |> 
#  janitor::clean_names()

kansas_tract <- tracts(state = "KS", year = 2022, progress_bar = FALSE) |> 
  janitor::clean_names() |> 
 mutate(census_tract = str_sub(geoid, 1, 9))

#kansas_zip <- zctas(state = "KS", year = 2010, progress_bar = FALSE) |> 
#  janitor::clean_names()
```

```{r}
#| label: mutate-props-virtual-data

#so postal_code = zip_code

#proposed viz: map of kansas, specifically northeast if possible
#county lines, plot a point for each SVH provider, then shade each county by the number of virtual visits and in person visits - might have to be more granular tbh because it's lowkey too granular

encounters_patients <- left_join(encounters, patients,
  by = join_by(patient_durable_key == durable_key)) |>
    select(visit_type_description, census_block_group_fips_code)

encounters_patients <- encounters_patients %>% 
  mutate(is_virtual_visit = str_detect(visit_type_description, "Virtual"),
         census_tract = substr(census_block_group_fips_code, 1, 9)) %>% 
  drop_na()

virtual_visit_tract <- encounters_patients |>
  group_by(census_tract) |>
  summarize(pct_visit_tract = mean(is_virtual_visit, na.rm = TRUE)) |>
  mutate(census_tract = as.character(census_tract),
         countyfp = substr(census_tract, 3, 5))

#virtual_visit_county <- encounters_patients |>
#  mutate(county_code = substr(census_tract, 3, 5)) |>
#  group_by(county_code) |>
#  summarize(pct_visit_county = mean(is_virtual_visit, na.rm = TRUE)) |>
#  drop_na(county_code)

kansas_tract_virtual <- kansas_tract |>
  left_join(virtual_visit_tract, by = join_by(census_tract == census_tract)) %>% 
    sf::st_as_sf()

#  left_join(virtual_visit_county, by = join_by(countyfp == county_code), relationship = "many-to-one") |>


#kansas_county_virtual <- kansas_county |> 
#  left_join(virtual_visit_county, by = join_by(countyfp == county_code), relationship = "many-to-one") |>
#  filter(countyfp %in% svh_counties$fips)
```

```{r}
#| label: plot-tract-version

ggplot() +
#graph tracts with aes(fill) prop of virtual visits
geom_sf(data = kansas_tract_virtual, aes(fill = pct_visit_tract)) +
    geom_sf(data = svh_locations, color = "red", size = 2, alpha = 0.7) +
scale_fill_viridis_c() +
  labs(title = "Percent of Virtual Visits and SVH Locations in Kansas",
       fill = "Percent") +
  theme_minimal() +
  theme(legend.position = "bottom") 

#insert manual diverging color scale here blue = #3B8794 yellow = #E8B447
#scale_fill_continuous_divergingx(palette = 'RdBu', mid = 0.5) 
  
```

```{r}
#| label: plot-county-version

#ggplot(kansas_county_virtual) +
#   #|> filter(str_remove(namelsad, " County") %in% svh_counties$county)
  #graph tracts with aes(fill) prop of virtual visits
 # geom_sf() +
  #graph points of hospitals
 # theme_minimal() #+
  #insert manual diverging color scale here blue = #3B8794 yellow = #E8B447
```
