---
title: "anric"
format: html
---
```{r}

patients |> summarise(across(everything(), ~ sum(is.na(.)))) |>
  pivot_longer(everything(), names_to = "column", values_to = "count") |>
  arrange(desc(count)) |>
  kable()
```

```{r}

diagnosis |> summarise(across(everything(), ~ sum(is.na(.)))) |>
  pivot_longer(everything(), names_to = "column", values_to = "count") |>
  arrange(desc(count)) |>
  kable()
```

```{r patients-cols}
names(patients)
```

```{r patients-vis}
ggplot(patients, aes(x = first_race, fill = first_race)) +
  geom_bar() +
  scale_y_log10() 

ggplot(patients, aes(x = "", fill = first_race)) +
  geom_bar(position = "fill")
ggplot(patients, aes(x = "", fill = vital_status)) +
  geom_bar(position = "fill")

```

```{r}
block_group <- patients |>
  count(census_block_group_fips_code)
```
```{r}
unique(patients$my_chart_status)
patients |>
  filter(is.na(patients$my_chart_status))
```

```{r}
dead_patients <- patients |>
  filter(vital_status == "Deceased")
unique(dead_patients$patient_birth_year_bin)

ggplot(dead_patients, aes(x = patient_birth_year_bin)) +
  geom_bar() +
  scale_y_log10()
```


```{r}
head(encounters, n = 10)
```

```{r}
dead_encounters <- inner_join(encounters, dead_patients, by = join_by(patient_durable_key == durable_key)) |>
  inner_join(diagnosis, join_by(diagnosis))

```

```{r}
encounters_patients <- inner_join(encounters, patients, by = join_by(patient_durable_key == durable_key))
```

```{r}
  select(date, department_key, encounter_key, 
         patient_durable_key, type, visit_type, provider_durable_key,    )
```

```{r}

dead_encounters |> summarise(across(everything(), ~ sum(is.na(.)))) |>
  pivot_longer(everything(), names_to = "column", values_to = "count") |>
  arrange(desc(count)) |>
  kable()

```

```{r}
diagnosis |> count(group_name)
diagnosis |> count(diagnosis_key) |> arrange(desc(n))

# Step 1 & 2: Count distinct B per A
diagnosis_conflict <- diagnosis %>%
  group_by(A) %>%
  summarise(
    n_B = n_distinct(B),          # number of unique B values
    B_values = list(unique(B)),   # actual B values
    .groups = "drop"
  ) %>%
  # Step 3: Keep only A values with more than 1 B
  filter(n_B > 1)

# View result
df_multiple_B_values
```

