---
title: "chelsea"
format: html
---
# Tiger Census
idk if eda is that useful for geospatial data 

# 3/21 : loading cleaned data

```{r}
#| label: read-clean-dfs
#| message: FALSE
library(tidyverse)
library(tidycensus)
library(tigris)

departments <- read_csv("~/chelseanathan0608@gmail.com - Google Drive/My Drive/Datafest/Clean-Data/departments.csv") %>%  mutate(county = str_to_title(county), department_name = str_to_title(department_name))
determinants <- read_csv("~/chelseanathan0608@gmail.com - Google Drive/My Drive/Datafest/Clean-Data/determinants.csv")
diagnosis <- read_csv("~/chelseanathan0608@gmail.com - Google Drive/My Drive/Datafest/Clean-Data/diagnosis.csv")
encounters <- read_csv("~/chelseanathan0608@gmail.com - Google Drive/My Drive/Datafest/Clean-Data/departments.csv")
patients <- read_csv("~/chelseanathan0608@gmail.com - Google Drive/My Drive/Datafest/Clean-Data/patients.csv")
providers <- read_csv("~/chelseanathan0608@gmail.com - Google Drive/My Drive/Datafest/Clean-Data/providers.csv") %>% 
  mutate(office_address = str_replace(office_address, "CT", "Ct"))
tigercensus <- read_csv("~/chelseanathan0608@gmail.com - Google Drive/My Drive/Datafest/Clean-Data/tigercensus.csv")
```

# Census
```{r}
ks_income_tract <- get_acs(
  geography = "tract",   # Choose county as our geographic unit
  variables = "B19013_001", 
  state = "KS",         
  year = 2022,
  geometry = TRUE)

ks_income_tract_county <- get_acs(
  geography = "county",   # Choose county as our geographic unit
  variables = "B19013_001", 
  state = "KS",         
  year = 2022)

ks_income_tract <- ks_income_tract |> 
  mutate(
  NAME = str_remove_all(NAME, ";"),
  NAME = str_remove_all(NAME, "Census Tract"),
  NAME = str_remove_all(NAME, "County"),
  NAME = str_remove_all(NAME, "Kansas"),
  NAME = str_squish(NAME)
) %>% 
  separate(NAME, into = c("tract", "county_name"), sep = " ")
```

SVH only covers 19 counties

```{r}
svh_counties <- tibble(
  county = c("Shawnee", "Riley", "Geary", "Dickinson", "Clay", "Wabaunsee", 
             "Morris", "Pottawatomie", "Jefferson", "Atchison", "Jackson", 
             "Nemaha", "Marshall", "Brown", "Lyon", "Franklin", "Osage", 
             "Coffey", "Douglas"),
  fips = c("20177", "20161", "20085", "20057", "20029", "20207", "20129", 
           "20149", "20103", "20015", "20099", "20135", "20121", "20021", 
           "20111", "20063", "20141", "20041", "20061")
)

ks_income_tract <- svh_counties %>% 
  left_join(ks_income_tract, by = join_by(county == county_name))
```


```{r}
#| message: FALSE
kansas_tract <- tigris::tracts(state = "KS", year = 2024, progress_bar = FALSE) |> 
  janitor::clean_names() 
```

```{r}
ks_sf_income_tract <- ks_income_tract %>%
  left_join(kansas_tract, by = c("GEOID" = "geoid")) %>% 
  sf::st_as_sf()

ggplot(ks_sf_income_tract) +
  geom_sf(aes(fill = estimate), color = NA) +
  scale_fill_viridis_c(name = "Median Household\nIncome ($)") +
  theme_minimal() +
  labs(title = "Median Household Income by Census Tract in Kansas")
```

